/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembersRouteImport } from './routes/members'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIdRouteImport } from './routes/members.$id'
import { Route as MembersIdEditRouteImport } from './routes/members.$id.edit'

const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdRoute = MembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MembersRoute,
} as any)
const MembersIdEditRoute = MembersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MembersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/members': typeof MembersRouteWithChildren
  '/members/$id': typeof MembersIdRouteWithChildren
  '/members/$id/edit': typeof MembersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/members': typeof MembersRouteWithChildren
  '/members/$id': typeof MembersIdRouteWithChildren
  '/members/$id/edit': typeof MembersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/auth': typeof AuthRoute
  '/members': typeof MembersRouteWithChildren
  '/members/$id': typeof MembersIdRouteWithChildren
  '/members/$id/edit': typeof MembersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/auth'
    | '/members'
    | '/members/$id'
    | '/members/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add' | '/auth' | '/members' | '/members/$id' | '/members/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/auth'
    | '/members'
    | '/members/$id'
    | '/members/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  AuthRoute: typeof AuthRoute
  MembersRoute: typeof MembersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$id/edit': {
      id: '/members/$id/edit'
      path: '/edit'
      fullPath: '/members/$id/edit'
      preLoaderRoute: typeof MembersIdEditRouteImport
      parentRoute: typeof MembersIdRoute
    }
  }
}

interface MembersIdRouteChildren {
  MembersIdEditRoute: typeof MembersIdEditRoute
}

const MembersIdRouteChildren: MembersIdRouteChildren = {
  MembersIdEditRoute: MembersIdEditRoute,
}

const MembersIdRouteWithChildren = MembersIdRoute._addFileChildren(
  MembersIdRouteChildren,
)

interface MembersRouteChildren {
  MembersIdRoute: typeof MembersIdRouteWithChildren
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersIdRoute: MembersIdRouteWithChildren,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  AuthRoute: AuthRoute,
  MembersRoute: MembersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
